#pragma once

#define RIFTLIFT_MAKE_STRING(value) #value
#define RIFTLIFT_STRINGIFY(value) RIFTLIFT_MAKE_STRING(value)

#define RIFTLIFT_RUNTIME_MAJOR_VERSION 1
#define RIFTLIFT_RUNTIME_MINOR_VERSION 0
#define RIFTLIFT_RUNTIME_PATCH_VERSION 0
#define RIFTLIFT_RUNTIME_BUILD_NUMBER 0

#define RIFTLIFT_RUNTIME_VERSION_STRING                                      \
	RIFTLIFT_STRINGIFY(RIFTLIFT_RUNTIME_MAJOR_VERSION.RIFTLIFT_RUNTIME_MINOR_VERSION. \
		RIFTLIFT_RUNTIME_PATCH_VERSION.RIFTLIFT_RUNTIME_BUILD_NUMBER)
#define RIFTLIFT_RUNTIME_VERSION_INT                                         \
	(RIFTLIFT_RUNTIME_MAJOR_VERSION << 24 | RIFTLIFT_RUNTIME_MINOR_VERSION << 16 | \
		RIFTLIFT_RUNTIME_PATCH_VERSION << 8 | RIFTLIFT_RUNTIME_BUILD_NUMBER)
